# Generated by Django 5.2.4 on 2025-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="stripe_coupon_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tax",
            name="stripe_tax_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
